import type { PaletteResult, SemanticTokens } from "../color/palette.js";
import type { ResolvedConfig } from "../config/schema.js";
import { SURFACES } from "../surfaces/presets.js";

/**
 * Generated brand guidelines. Authored from the same config + palette the assets
 * use, so the docs can never drift from what's actually produced.
 */

function tokenTable(t: SemanticTokens): string {
  const rows = Object.entries(t)
    .map(([k, v]) => `| \`${k}\` | \`${v}\` |`)
    .join("\n");
  return `| Token | Value |\n|---|---|\n${rows}`;
}

export function renderGuidelines(cfg: ResolvedConfig, result: PaletteResult): string {
  const { layout, typography, brand } = cfg;
  const worstText = Math.min(...result.audit.map((a) => a.ratio));

  return `# ${brand.title} — Brand Guidelines

_Generated by brandkit-generator. Do not hand-edit — regenerate from \`brandkit.config.yaml\`._

## The mark

The mark is the CI/CD loop with the highlighted **P**. Ship these variants:

| Variant | File | Use |
|---|---|---|
| Duotone (light) | \`logo/mark-duotone-light.svg\` | Default, on light backgrounds |
| Duotone (dark) | \`logo/mark-duotone-dark.svg\` | On dark backgrounds |
| Mono | \`logo/mark-mono.svg\` | Single-color contexts — inherits \`currentColor\` |
| On accent | \`logo/mark-on-accent.svg\` | White knockout, on the brand blue |

**Small sizes use the mark only** — never the full lockup below ${layout.minSizePx}px. Favicons floor at ${layout.faviconFloorPx}px.

## Lockups

Pair the mark with the wordmark **${brand.title}** (${typography.title.family} ${typography.title.weight}, the first word bold and the rest regular).

- **Horizontal** — \`logo/lockup-horizontal-{light,dark}.svg\` — default for headers, docs, README.
- **Vertical** — \`logo/lockup-vertical-{light,dark}.svg\` — for square/centered placements.
- **Wordmark** — \`logo/wordmark-{light,dark}.svg\` — the logotype alone, no mark, for text-only contexts.

Alignment is optical: the wordmark cap-height is centered on the mark.

## Clear space & minimum size

- **Clear space:** keep a margin of **${layout.clearSpace} × X** on all sides, where **X = the mark height**. This ratio holds at every size — never use a fixed pixel value.
- **Lockup gap:** the mark-to-wordmark gap is **${layout.gap} × X**.
- **Minimum size:** ${layout.minSizePx}px for the mark in digital use; ${layout.faviconFloorPx}px favicon floor.

## Do / Don't

**Do**
- Use the provided variants and tokens.
- Preserve the mark's aspect ratio; scale uniformly.
- Give the mark its clear space.

**Don't**
- Stretch, skew, rotate, or add effects to the mark.
- Recolor the mark outside the approved palette.
- Place the full lockup below the minimum size — use the mark.
- Put the mark on a low-contrast background.

## Color

Palette derived perceptually (OKLCH) from the primary \`${cfg.color.primary}\`. Usage follows ~**60/30/10** (surface / secondary / accent). Every foreground/background pairing meets **WCAG ${cfg.palette.contrast}** (lowest audited ratio ${worstText.toFixed(2)}:1). Full ramps and per-pairing audit live in \`brand-spec.md\`; machine-readable tokens in \`tokens/tokens.json\` (DTCG) and \`tokens/tailwind.theme.css\`.

### Light theme

${tokenTable(result.themes.light)}

### Dark theme

${tokenTable(result.themes.dark)}

## Typography

| Role | Family | Weight |
|---|---|---|
| Display / headings | ${typography.title.family} | ${typography.title.weight} |
| Body / subtitle | ${typography.body.family} | ${typography.body.weight} |
| Code / mono | ${typography.mono.family} | ${typography.mono.weight} |

Modular type scale, ratio **${typography.scale}**, base **${typography.base}px**.

## Applications

| Surface | Size | Use |
|---|---|---|
${SURFACES.map((s) => `| ${s.name} | ${s.w}×${s.h} | ${s.use} |`).join("\n")}

Every generated asset is indexed in \`manifest.json\` with dimensions and intended use.
`;
}
